name: var_test

on:
  workflow_dispatch:

jobs:
  run_var_test_jobs:
    runs-on: ubuntu-latest
    environment: 
      name: var_test

    steps:
      - uses: actions/checkout@v3

      - name: test parameter expansion
        run: |
          echo "${${{ vars.HELLO_WORLD }}:-${{ secrets.HELLO_WORLD}} }"
